/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  LogType: "emptied" | "mutation"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Log: { // root type
    amount?: number | null; // Int
    date: string; // String!
    id: string; // String!
    slug?: string | null; // String
    title?: string | null; // String
    type: NexusGenEnums['LogType']; // LogType!
  }
  Query: {};
  StockItem: { // root type
    amount: number; // Int!
    slug: string; // String!
    title: string; // String!
  }
  Storage: { // root type
    canEmpty: boolean; // Boolean!
    id: string; // String!
    order: number; // Int!
    title: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Log: { // field return type
    amount: number | null; // Int
    date: string; // String!
    id: string; // String!
    slug: string | null; // String
    title: string | null; // String
    type: NexusGenEnums['LogType']; // LogType!
  }
  Query: { // field return type
    storages: NexusGenRootTypes['Storage'][]; // [Storage!]!
  }
  StockItem: { // field return type
    amount: number; // Int!
    slug: string; // String!
    title: string; // String!
  }
  Storage: { // field return type
    canEmpty: boolean; // Boolean!
    id: string; // String!
    items: NexusGenRootTypes['StockItem'][]; // [StockItem!]!
    logs: NexusGenRootTypes['Log'][]; // [Log!]!
    order: number; // Int!
    title: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Log: { // field return type name
    amount: 'Int'
    date: 'String'
    id: 'String'
    slug: 'String'
    title: 'String'
    type: 'LogType'
  }
  Query: { // field return type name
    storages: 'Storage'
  }
  StockItem: { // field return type name
    amount: 'Int'
    slug: 'String'
    title: 'String'
  }
  Storage: { // field return type name
    canEmpty: 'Boolean'
    id: 'String'
    items: 'StockItem'
    logs: 'Log'
    order: 'Int'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Query: {
    storages: { // args
      id?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}